apiVersion : apps/v1
kind: Deployment
metadata:
  name: weighttracker 
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: weighttracker
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: weighttracker 
    spec:
      containers:
        - name: weighttracker
          image: weighttrackeracr.azurecr.io/weighttracker
          ports:
          - containerPort: 80
          envFrom:
          - secretRef:
              name: secret
